sq: Improve reporting of verification errors.
  - We now explain the errors like sequoia-sop:

    % sq verify --detached msg.sig --signer-cert ... < msg
    Error verifying checksum from 39D100AB67D5BD8C04010205FB3751F1587DAEF1:
               Policy rejected non-revocation signature (Binary) requiring collision resistance
      because: MD5 is not considered secure since 1997-02-01T00:00:00Z
    1 bad checksum.
    Error: Verification failed

  - Fixes #676.